---
apiVersion: v1
kind: Service
metadata:
  name: sparta-db-svc
  namespace: default

spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: sparta-db # this label connect this service to the deployment
  type: NodePort # also use LoadBalancer - for local use cluster IP
