# YAML is case sensitive
# use spaces not a tab

apiVersion: apps/v1 # specify api to use for deployment
kind: Deployment # kind of service/object you want to create
metadata:
  name: sparta-app-deployment # name the deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: sparta-app # look for this label/tag to match with k8 service
  # create a replica set of this with instances/pods
  replicas: 3
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
        - name: sparta-app
          image: callumreanderson/sparta_app_image:v1 # the image you created to run nginx in a container
          ports:
            - containerPort: 80
