---
apiVersion: v1
kind: Service
metadata:
  name: sparta-app-svc
  namespace: default

spec:
  ports:
    - nodePort: 30000 # range is 30000-32768
      port: 80
      targetPort: 80
  selector:
    app: sparta-app # this label connect this service to the deployment
  type: NodePort # also use LoadBalancer - for local use cluster IP
